import type { ChartSpec } from "./chartTypes";

/**
 * E12-S4 — an export that does not carry its provenance is a screenshot with
 * extra steps. Every CSV and every printed page produced from an analytics
 * surface opens with the period, the active filters, the scope and the
 * generation timestamp, so a figure pasted into a board pack can still be
 * traced back to the query that produced it.
 */

export interface Provenance {
  surface: string;
  periodLabel: string;
  periodRange: string;
  scopeStatement: string;
  branchLabel: string;
  basisInWords: string;
  filters: string[];
  generatedAt: string;
  generatedBy: string;
  simulatedClock: string;
}

const esc = (v: string | number): string => {
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export function provenanceRows(p: Provenance): string[][] {
  return [
    ["Pravaah — Bhushan Corp Operations Platform"],
    ["Surface", p.surface],
    ["Period", `${p.periodLabel} (${p.periodRange})`],
    ["Branch scope", p.branchLabel],
    ["Scope applied", p.scopeStatement],
    ["Comparison basis", p.basisInWords],
    ["Active filters", p.filters.join(" · ") || "None"],
    ["Generated at", p.generatedAt],
    ["Generated by", p.generatedBy],
    ["Simulated platform clock", p.simulatedClock],
    ["Note", "Figures computed from platform records by the shared KPI implementation. No figure on this export was entered by hand."],
    [],
  ];
}

export function chartToRows(spec: ChartSpec): string[][] {
  const header = [spec.xLabel, ...spec.series.map((s) => s.label)];
  const body = spec.data.map((d) => [d.label, ...spec.series.map((s) => String(d.values[s.key] ?? ""))]);
  return [[spec.title], header, ...body, []];
}

export function buildCsv(p: Provenance, sections: { title: string; rows: string[][] }[]): string {
  const out: string[][] = [...provenanceRows(p)];
  for (const s of sections) {
    out.push([s.title]);
    out.push(...s.rows);
    out.push([]);
  }
  return out.map((r) => r.map(esc).join(",")).join("\r\n");
}

export function downloadCsv(filename: string, csv: string): void {
  // ﻿ so Excel opens the ₹ sign and Indian grouping without mangling them.
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Print-ready PDF. The browser's own print pipeline is the PDF writer; the
 * provenance block is already in the DOM behind `print:block`, so what reaches
 * the page carries the same header as the CSV.
 */
export function printSurface(): void {
  window.print();
}
